apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{APP_NAME}}
  namespace: {{NAME_SPACE}}
  labels:
    app: {{APP_NAME}}
spec:
  replicas: 1
  selector:
      app: {{APP_NAME}}
  template:
    metadata:
      labels:
        app: {{APP_NAME}}
    spec:
      containers:
      - name: {{APP_NAME}}
        image: {{IMAGES_URL}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80